# Generated by Django 4.1.2 on 2022-10-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=15)),
                ('Desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
